FROM tomee:8-jdk-7.0.0-plus
ADD target/registry-server.war /usr/local/tomee/webapps/registry-server.war
EXPOSE 8080

#FROM jboss/wildfly
#ADD target/registry-server.war /opt/jboss/wildfly/standalone/deployments/registry-server.war
#EXPOSE 8080